<?xml version="1.0" encoding="utf-8"?>
<Database Name="CSCDatabase" Class="CSCDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ZVONEPC;Initial Catalog=CSCDatabase;Integrated Security=True" SettingsObjectName="BatchAnalysisModel.Properties.Settings" SettingsPropertyName="CSCDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Pitanje" Member="Pitanjes">
    <Type Name="Pitanje">
      <Column Name="IDZadatka" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDPitanja" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDPredmeta" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StazaPitanja" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="IDStudent" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProsjecnaOcjena" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ProsjecanRang" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="RangpriUpisu" Type="System.Int32" DbType="SmallInt" CanBeNull="true" />
      <Column Name="upsize_ts" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
    </Type>
  </Table>
  <Table Name="dbo.StudentskoRjesenje" Member="StudentskoRjesenjes">
    <Type Name="StudentskoRjesenje">
      <Column Name="IDRjesenja" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDStudent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDZadatka" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Preuzeo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Predao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Bodovi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IDPredmeta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TekstRjesenja" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="upsize_ts" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
    </Type>
  </Table>
</Database>