#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchAnalysisModel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CSCDatabase")]
	public partial class CSCDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPitanje(Pitanje instance);
    partial void UpdatePitanje(Pitanje instance);
    partial void DeletePitanje(Pitanje instance);
    partial void InsertStudent(Student instance);
    partial void UpdateStudent(Student instance);
    partial void DeleteStudent(Student instance);
    partial void InsertStudentskoRjesenje(StudentskoRjesenje instance);
    partial void UpdateStudentskoRjesenje(StudentskoRjesenje instance);
    partial void DeleteStudentskoRjesenje(StudentskoRjesenje instance);
    #endregion
		
		public CSCDataClassesDataContext() : 
				base(global::BatchAnalysisModel.Properties.Settings.Default.CSCDatabaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CSCDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSCDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSCDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSCDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Pitanje> Pitanjes
		{
			get
			{
				return this.GetTable<Pitanje>();
			}
		}
		
		public System.Data.Linq.Table<Student> Students
		{
			get
			{
				return this.GetTable<Student>();
			}
		}
		
		public System.Data.Linq.Table<StudentskoRjesenje> StudentskoRjesenjes
		{
			get
			{
				return this.GetTable<StudentskoRjesenje>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pitanje")]
	public partial class Pitanje : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDZadatka;
		
		private int _IDPitanja;
		
		private int _IDPredmeta;
		
		private string _StazaPitanja;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDZadatkaChanging(int value);
    partial void OnIDZadatkaChanged();
    partial void OnIDPitanjaChanging(int value);
    partial void OnIDPitanjaChanged();
    partial void OnIDPredmetaChanging(int value);
    partial void OnIDPredmetaChanged();
    partial void OnStazaPitanjaChanging(string value);
    partial void OnStazaPitanjaChanged();
    #endregion
		
		public Pitanje()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDZadatka", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int IDZadatka
		{
			get
			{
				return this._IDZadatka;
			}
			set
			{
				if ((this._IDZadatka != value))
				{
					this.OnIDZadatkaChanging(value);
					this.SendPropertyChanging();
					this._IDZadatka = value;
					this.SendPropertyChanged("IDZadatka");
					this.OnIDZadatkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPitanja", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDPitanja
		{
			get
			{
				return this._IDPitanja;
			}
			set
			{
				if ((this._IDPitanja != value))
				{
					this.OnIDPitanjaChanging(value);
					this.SendPropertyChanging();
					this._IDPitanja = value;
					this.SendPropertyChanged("IDPitanja");
					this.OnIDPitanjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPredmeta", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDPredmeta
		{
			get
			{
				return this._IDPredmeta;
			}
			set
			{
				if ((this._IDPredmeta != value))
				{
					this.OnIDPredmetaChanging(value);
					this.SendPropertyChanging();
					this._IDPredmeta = value;
					this.SendPropertyChanged("IDPredmeta");
					this.OnIDPredmetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StazaPitanja", DbType="NVarChar(200)")]
		public string StazaPitanja
		{
			get
			{
				return this._StazaPitanja;
			}
			set
			{
				if ((this._StazaPitanja != value))
				{
					this.OnStazaPitanjaChanging(value);
					this.SendPropertyChanging();
					this._StazaPitanja = value;
					this.SendPropertyChanged("StazaPitanja");
					this.OnStazaPitanjaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Student")]
	public partial class Student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDStudent;
		
		private System.Nullable<double> _ProsjecnaOcjena;
		
		private System.Nullable<short> _ProsjecanRang;
		
		private System.Nullable<int> _RangpriUpisu;
		
		private System.Data.Linq.Binary _upsize_ts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDStudentChanging(int value);
    partial void OnIDStudentChanged();
    partial void OnProsjecnaOcjenaChanging(System.Nullable<double> value);
    partial void OnProsjecnaOcjenaChanged();
    partial void OnProsjecanRangChanging(System.Nullable<short> value);
    partial void OnProsjecanRangChanged();
    partial void OnRangpriUpisuChanging(System.Nullable<int> value);
    partial void OnRangpriUpisuChanged();
    partial void Onupsize_tsChanging(System.Data.Linq.Binary value);
    partial void Onupsize_tsChanged();
    #endregion
		
		public Student()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDStudent", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int IDStudent
		{
			get
			{
				return this._IDStudent;
			}
			set
			{
				if ((this._IDStudent != value))
				{
					this.OnIDStudentChanging(value);
					this.SendPropertyChanging();
					this._IDStudent = value;
					this.SendPropertyChanged("IDStudent");
					this.OnIDStudentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProsjecnaOcjena", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> ProsjecnaOcjena
		{
			get
			{
				return this._ProsjecnaOcjena;
			}
			set
			{
				if ((this._ProsjecnaOcjena != value))
				{
					this.OnProsjecnaOcjenaChanging(value);
					this.SendPropertyChanging();
					this._ProsjecnaOcjena = value;
					this.SendPropertyChanged("ProsjecnaOcjena");
					this.OnProsjecnaOcjenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProsjecanRang", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> ProsjecanRang
		{
			get
			{
				return this._ProsjecanRang;
			}
			set
			{
				if ((this._ProsjecanRang != value))
				{
					this.OnProsjecanRangChanging(value);
					this.SendPropertyChanging();
					this._ProsjecanRang = value;
					this.SendPropertyChanged("ProsjecanRang");
					this.OnProsjecanRangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RangpriUpisu", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> RangpriUpisu
		{
			get
			{
				return this._RangpriUpisu;
			}
			set
			{
				if ((this._RangpriUpisu != value))
				{
					this.OnRangpriUpisuChanging(value);
					this.SendPropertyChanging();
					this._RangpriUpisu = value;
					this.SendPropertyChanged("RangpriUpisu");
					this.OnRangpriUpisuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upsize_ts", AutoSync=AutoSync.Always, DbType="rowversion", CanBeNull=true, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary upsize_ts
		{
			get
			{
				return this._upsize_ts;
			}
			set
			{
				if ((this._upsize_ts != value))
				{
					this.Onupsize_tsChanging(value);
					this.SendPropertyChanging();
					this._upsize_ts = value;
					this.SendPropertyChanged("upsize_ts");
					this.Onupsize_tsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StudentskoRjesenje")]
	public partial class StudentskoRjesenje : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDRjesenja;
		
		private System.Nullable<int> _IDStudent;
		
		private System.Nullable<int> _IDZadatka;
		
		private System.Nullable<System.DateTime> _Preuzeo;
		
		private System.Nullable<System.DateTime> _Predao;
		
		private System.Nullable<double> _Bodovi;
		
		private System.Nullable<int> _IDPredmeta;
		
		private string _TekstRjesenja;
		
		private System.Data.Linq.Binary _upsize_ts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDRjesenjaChanging(int value);
    partial void OnIDRjesenjaChanged();
    partial void OnIDStudentChanging(System.Nullable<int> value);
    partial void OnIDStudentChanged();
    partial void OnIDZadatkaChanging(System.Nullable<int> value);
    partial void OnIDZadatkaChanged();
    partial void OnPreuzeoChanging(System.Nullable<System.DateTime> value);
    partial void OnPreuzeoChanged();
    partial void OnPredaoChanging(System.Nullable<System.DateTime> value);
    partial void OnPredaoChanged();
    partial void OnBodoviChanging(System.Nullable<double> value);
    partial void OnBodoviChanged();
    partial void OnIDPredmetaChanging(System.Nullable<int> value);
    partial void OnIDPredmetaChanged();
    partial void OnTekstRjesenjaChanging(string value);
    partial void OnTekstRjesenjaChanged();
    partial void Onupsize_tsChanging(System.Data.Linq.Binary value);
    partial void Onupsize_tsChanged();
    #endregion
		
		public StudentskoRjesenje()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDRjesenja", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int IDRjesenja
		{
			get
			{
				return this._IDRjesenja;
			}
			set
			{
				if ((this._IDRjesenja != value))
				{
					this.OnIDRjesenjaChanging(value);
					this.SendPropertyChanging();
					this._IDRjesenja = value;
					this.SendPropertyChanged("IDRjesenja");
					this.OnIDRjesenjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDStudent", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> IDStudent
		{
			get
			{
				return this._IDStudent;
			}
			set
			{
				if ((this._IDStudent != value))
				{
					this.OnIDStudentChanging(value);
					this.SendPropertyChanging();
					this._IDStudent = value;
					this.SendPropertyChanged("IDStudent");
					this.OnIDStudentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDZadatka", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> IDZadatka
		{
			get
			{
				return this._IDZadatka;
			}
			set
			{
				if ((this._IDZadatka != value))
				{
					this.OnIDZadatkaChanging(value);
					this.SendPropertyChanging();
					this._IDZadatka = value;
					this.SendPropertyChanged("IDZadatka");
					this.OnIDZadatkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Preuzeo", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> Preuzeo
		{
			get
			{
				return this._Preuzeo;
			}
			set
			{
				if ((this._Preuzeo != value))
				{
					this.OnPreuzeoChanging(value);
					this.SendPropertyChanging();
					this._Preuzeo = value;
					this.SendPropertyChanged("Preuzeo");
					this.OnPreuzeoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Predao", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> Predao
		{
			get
			{
				return this._Predao;
			}
			set
			{
				if ((this._Predao != value))
				{
					this.OnPredaoChanging(value);
					this.SendPropertyChanging();
					this._Predao = value;
					this.SendPropertyChanged("Predao");
					this.OnPredaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bodovi", DbType="Float", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<double> Bodovi
		{
			get
			{
				return this._Bodovi;
			}
			set
			{
				if ((this._Bodovi != value))
				{
					this.OnBodoviChanging(value);
					this.SendPropertyChanging();
					this._Bodovi = value;
					this.SendPropertyChanged("Bodovi");
					this.OnBodoviChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPredmeta", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> IDPredmeta
		{
			get
			{
				return this._IDPredmeta;
			}
			set
			{
				if ((this._IDPredmeta != value))
				{
					this.OnIDPredmetaChanging(value);
					this.SendPropertyChanging();
					this._IDPredmeta = value;
					this.SendPropertyChanged("IDPredmeta");
					this.OnIDPredmetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TekstRjesenja", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string TekstRjesenja
		{
			get
			{
				return this._TekstRjesenja;
			}
			set
			{
				if ((this._TekstRjesenja != value))
				{
					this.OnTekstRjesenjaChanging(value);
					this.SendPropertyChanging();
					this._TekstRjesenja = value;
					this.SendPropertyChanged("TekstRjesenja");
					this.OnTekstRjesenjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upsize_ts", AutoSync=AutoSync.Always, DbType="rowversion", CanBeNull=true, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary upsize_ts
		{
			get
			{
				return this._upsize_ts;
			}
			set
			{
				if ((this._upsize_ts != value))
				{
					this.Onupsize_tsChanging(value);
					this.SendPropertyChanging();
					this._upsize_ts = value;
					this.SendPropertyChanged("upsize_ts");
					this.Onupsize_tsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
