//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DrawLine.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DRAWLITYPE                  129
#define IDD_DIALOG1                     130
#define IDD_DIALOG2                     131
#define IDD_DIALOG3                     132
#define IDD_DIALOG4                     133
#define IDD_DIALOG5                     134
#define IDD_DIALOG6                     135
#define IDD_DIALOG7                     136
#define IDD_DIALOG8                     137
#define IDD_DIALOG9                     138
#define IDC1_VERTEX_NUM                 1000
#define IDC2_VERTEX_NUM                 1001
#define IDC2_X_COORD                    1002
#define IDC2_Y_COORD                    1003
#define IDC2_Z_COORD                    1004
#define IDC3_X1                         1005
#define IDC3_Y1                         1006
#define IDC3_X2                         1007
#define IDC3_Y2                         1008
#define IDC3_RECT_WIDTH                 1009
#define IDC3_RECT_HEIGHT                1010
#define IDC3_EPS                        1011
#define IDC3_MAX_ITER_NUM               1012
#define IDC4_EPS                        1013
#define IDC4_MAX_ITER_NUM               1014
#define IDC4_RECT_WIDTH                 1015
#define IDC4_RECT_HEIGHT                1016
#define IDC4_X1                         1017
#define IDC4_Y1                         1018
#define IDC4_X2                         1019
#define IDC4_Y2                         1020
#define IDC4_CRE                        1021
#define IDC4_CIM                        1022
#define IDC5_UPPER_Z_COORD              1023
#define IDC5_LOWER_Z_COORD              1024
#define IDC6_X_COORD                    1025
#define IDC6_Y_COORD                    1026
#define IDC6_Z_COORD                    1027
#define IDC7_X                          1028
#define IDC7_T                          1030
#define IDC8_VERT_NUM                   1031
#define IDC9_X                          1032
#define IDC9_Y                          1033
#define ID_EXERC_DRAWLINE               32771
#define ID_EXERC_DRAW_CONVEX_POLY       32772
#define ID_EXERC_DRAW_POLY              32773
#define ID_CHECK_POINT_BODY             32774
#define ID_VIEW_TRANSF                  32775
#define ID_HIDDEN_LINES                 32776
#define ID_QUAD_FUNC                    32777
#define ID_CUBIC_FUNC                   32778
#define ID_BEZIER_FUNC                  32779
#define ID_MANDELBROT                   32780
#define ID_JULIA                        32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1034
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
